const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const { readSessionFile, readSessionDisplayHeader } = require('../read-session-file');

function mkTmp() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'switchboard-slash-'));
}

function cleanup(dir) {
  fs.rmSync(dir, { recursive: true, force: true });
}

function write(dir, sessionId, entries) {
  const filePath = path.join(dir, `${sessionId}.jsonl`);
  fs.writeFileSync(filePath, entries.map(e => JSON.stringify(e)).join('\n') + '\n', 'utf8');
  return filePath;
}

// The exact records Claude Code writes into the NEW transcript /clear opens.
const CLEAR_BOOKKEEPING = [
  { type: 'mode', mode: 'normal' },
  { type: 'file-history-snapshot', messageId: 'm1' },
  {
    type: 'user',
    isMeta: true,
    timestamp: '2026-08-26T07:44:02.583Z',
    message: {
      role: 'user',
      content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>',
    },
  },
  {
    type: 'user',
    timestamp: '2026-08-26T07:44:02.578Z',
    message: {
      role: 'user',
      content: '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>',
    },
  },
  {
    type: 'system',
    subtype: 'local_command',
    timestamp: '2026-08-26T07:44:02.582Z',
    content: '<local-command-stdout></local-command-stdout>',
  },
];

test('a transcript holding only /clear bookkeeping is not indexed at all', () => {
  const tmp = mkTmp();
  try {
    const filePath = write(tmp, 'cleared', CLEAR_BOOKKEEPING);
    assert.equal(readSessionFile(filePath, 'folder-x', '/some/project'), null,
      '/clear opens a new transcript with no conversation in it — indexing it puts a phantom session in the sidebar');
    assert.equal(readSessionDisplayHeader(filePath), null);
  } finally {
    cleanup(tmp);
  }
});

test('a session started by /clear is titled by its first real prompt', () => {
  const tmp = mkTmp();
  try {
    const filePath = write(tmp, 'after-clear', [
      ...CLEAR_BOOKKEEPING,
      { type: 'user', timestamp: '2026-08-26T07:45:00.000Z', message: { role: 'user', content: 'fix the watcher' } },
      { type: 'assistant', timestamp: '2026-08-26T07:45:01.000Z', message: { role: 'assistant', content: 'on it' } },
    ]);

    const row = readSessionFile(filePath, 'folder-x', '/some/project');
    assert.equal(row.summary, 'fix the watcher');
    assert.equal(row.firstPrompt, 'fix the watcher');
    assert.equal(readSessionDisplayHeader(filePath).summary, 'fix the watcher');
  } finally {
    cleanup(tmp);
  }
});

test('a session whose only user turn is a slash command is titled by that command', () => {
  const tmp = mkTmp();
  try {
    const filePath = write(tmp, 'command-only', [
      {
        type: 'user',
        timestamp: '2026-08-26T07:44:02.578Z',
        message: {
          role: 'user',
          content: '<command-name>/code-review</command-name>\n<command-message>code-review</command-message>\n<command-args>high</command-args>',
        },
      },
      { type: 'assistant', timestamp: '2026-08-26T07:44:03.000Z', message: { role: 'assistant', content: 'reviewing' } },
    ]);

    // The raw record would render as "/code-review code-review </command-args"
    // once cleanDisplayName strips the tags.
    const row = readSessionFile(filePath, 'folder-x', '/some/project');
    assert.equal(row.summary, '/code-review high');
    assert.equal(readSessionDisplayHeader(filePath).summary, '/code-review high');
  } finally {
    cleanup(tmp);
  }
});

test('a bare /model with no answer yet is bookkeeping, not a session', () => {
  const tmp = mkTmp();
  try {
    const filePath = write(tmp, 'model-only', [
      {
        type: 'user',
        timestamp: '2026-08-26T07:44:02.578Z',
        message: {
          role: 'user',
          content: '<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>',
        },
      },
    ]);
    assert.equal(readSessionFile(filePath, 'folder-x', '/some/project'), null);
    assert.equal(readSessionDisplayHeader(filePath), null);
  } finally {
    cleanup(tmp);
  }
});

test("a command's own output is not a prompt either", () => {
  const tmp = mkTmp();
  try {
    // /model logs its confirmation back as a `user` record; before the fix it
    // became the title of every session where /model preceded the first prompt.
    const filePath = write(tmp, 'model-then-work', [
      ...CLEAR_BOOKKEEPING,
      {
        type: 'user',
        timestamp: '2026-08-26T07:45:00.000Z',
        message: {
          role: 'user',
          content: '<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>sonnet</command-args>',
        },
      },
      {
        type: 'user',
        timestamp: '2026-08-26T07:45:01.000Z',
        message: { role: 'user', content: '<local-command-stdout>Set model to Sonnet 5</local-command-stdout>' },
      },
      { type: 'user', timestamp: '2026-08-26T07:46:00.000Z', message: { role: 'user', content: 'add the motion sensor' } },
      { type: 'assistant', timestamp: '2026-08-26T07:46:01.000Z', message: { role: 'assistant', content: 'on it' } },
    ]);

    assert.equal(readSessionFile(filePath, 'folder-x', '/some/project').summary, 'add the motion sensor');
    assert.equal(readSessionDisplayHeader(filePath).summary, 'add the motion sensor');
  } finally {
    cleanup(tmp);
  }
});

test('a scheduled-task prompt still wins over a leading slash command', () => {
  const tmp = mkTmp();
  try {
    const filePath = write(tmp, 'scheduled', [
      ...CLEAR_BOOKKEEPING,
      {
        type: 'user',
        timestamp: '2026-08-26T07:45:00.000Z',
        message: { role: 'user', content: '<scheduled-task name="nightly introspection">run it</scheduled-task>' },
      },
      { type: 'assistant', timestamp: '2026-08-26T07:45:01.000Z', message: { role: 'assistant', content: 'ok' } },
    ]);
    assert.equal(readSessionFile(filePath, 'folder-x', '/some/project').summary,
      'Scheduled: nightly introspection');
  } finally {
    cleanup(tmp);
  }
});
